env:
  names:
    - BabyAI-GoToLocal-v0
    - BabyAI-GoToLocalS5N2-v0
    - BabyAI-GoToLocalS6N2-v0
    - BabyAI-GoToLocalS6N3-v0
    - BabyAI-GoToLocalS6N4-v0
    - BabyAI-GoToLocalS7N4-v0
    - BabyAI-GoToLocalS7N5-v0
    - BabyAI-GoToLocalS8N2-v0
    - BabyAI-GoToLocalS8N3-v0
    - BabyAI-GoToLocalS8N4-v0
    - BabyAI-GoToLocalS8N5-v0
    - BabyAI-GoToLocalS8N6-v0
    - BabyAI-GoToLocalS8N7-v0

training:
  episodes: 10000
  gamma: 0.99
  lr: 0.0003

model:
  hidden_dim: 128